# define credentials

AWS_ACCESS_KEY = "{/YOUR_ACCESS_KEY}}"
AWS_ACCESS_SECRET_KEY = "{/YOUR_ACCESS_SECRET_KEY}"

SNOWFLAKE_USERNAME = "{/YOUR_USERNAME}"
SNOWFLAKE_PASSWORD = "{/YOUR_PASSWORD}"
SNOWFLAKE_ACCOUNT = "{/YOUR_ACCOUNT}"
SNOWFLAKE_WAREHOUSE = "{/YOUR_WAREHOUSE}"
SNOWFLAKE_DATABASE = "{/YOUR_DATABASE}"
SNOWFLAKE_SCHEMA = "{/YOUR_SCHEMA}"
SNOWFLAKE_ROLE = "{/YOUR_ROLE}"
